name: twilio_programmable_video_platform_interface
description: A common platform interface for the programmable_video plugin.
version: 0.7.1
homepage: https://gitlab.com/twilio-flutter/programmable-video
repository: https://gitlab.com/twilio-flutter/programmable-video/-/tree/master/programmable_video_platform_interface
issue_tracker: https://gitlab.com/twilio-flutter/programmable-video/issues
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  enum_to_string: ^2.0.1
  plugin_platform_interface: ^2.1.2
  collection: ^1.16.0
  dartlin: ^0.6.3
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  build_runner: ^1.10.0